### PR TITLE
Align all flyout components to be overlay kind and add close button X in header

### LINKED ISSUE #296: [BUG] Alert details flyout's responsiveness
**What is the bug?**
The table and the push flyout do not resize gracefully in the `Alerts by triggers` list in the Alerting plugin for different screen sizes:
1. The elements in the table header don't stack but move outside of the table
2. On the smaller screens the table becomes unusable
3. On the screens smaller than about 990px the flyout switches to overlay type overlapping and blocking the table.
4. The monitor name is truncated even if there is enough space to accommodate the full name

**How can one reproduce the bug?**
Steps to reproduce the behavior (assuming the `Alerts by triggers` table is not empty):
1. Go to the 'Alerting' plugin - this will land you on `Alerts by triggers` page
5. Click on the "burger" icon in the top left corner of the screen
6. Click on the last item in the main navigation panel `Dock navigation`
7. Click on the number of alerts in the second column of the table - the flyout appears in the right part of the screen and resizes the table
8. Resize the browser window to less than ~1700px
9. Then change the size of your browser window to less than ~990px

**What is the expected behavior?**
All elements of the table should resize gracefully. The push flyout width/proportion should adjust to the screen size. 
On the screens smaller than ~990px the overlay type flyout should not obscure the table (By setting `ownFocus={false}`, the underlying page content will be visible and clickable.). The monitor name column should be wider when screen size permits to show the names of the monitors without truncation.

**What is your host/environment?**
 - OS: macOS
 - Version 12.4
 - Plugins `Alerting`
 - Browser `Chrome`, `Firefox`, `Safari`

**Do you have any screenshots?**
Screen Shot 2022-08-03 at 11 30 42 PM

Screen Shot 2022-08-03 at 11 31 00 PM

Screen Shot 2022-08-03 at 11 31 26 PM

Screen Shot 2022-08-03 at 11 28 56 PM

Screen Shot 2022-08-04 at 12 03 42 AM

**Do you have any additional context?**
The problems with responsiveness seem to be amplified by introducing the `dock navigation` feature in the main menu in combination with the push flyout use. The `pushMinBreakpoint` for the overlay flyout might need to be reviewed along with the docked navigation behavior for the small screens.

### PR DESCRIPTION
**Pull request by djindjic**
### Description
Refactored all `Flyout's` to be as `type="overlay"` (default type value)
 
### Issues Resolved
Resolves #296 #297 #298 #299 #300 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js [hunk 1]
```diff
@@ -70,10 +70,16 @@ export default class FindingFlyout extends Component {
 
   closeFlyout = () => {
     this.setState({ isFlyoutOpen: false });
+
+    const { dashboardFlyoutIsOpen = false, closeFlyout } = this.props;
+
+    if (typeof closeFlyout === 'function') {
+      if (dashboardFlyoutIsOpen) closeFlyout();
```
Comment (amsiglan) [inline public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js:77]: club the two if conditions?

Comment (djindjic) [reply public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js:77]: I've used defensive mimicking on already existing idea few lines above. I could actually simplify.
image

Comment (djindjic) [reply public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js]: fixed

File: public/components/Flyout/flyouts/__snapshots__/flyouts.test.js.snap [hunk 2]
```diff
@@ -8,33 +8,41 @@ Object {
...
+    justifyContent="flexStart"
   >
-    <h2>
-      Alerts by undefined
-    </h2>
-  </EuiText>,
+    <EuiFlexItem>
+      <EuiFlexGroup
+        alignItems="center"
+      >
```
Comment (amsiglan) [inline public/components/Flyout/flyouts/__snapshots__/flyouts.test.js.snap:24]: Since there is only one flexitem inside, do we need this flex-group?

Comment (amsiglan) [reply public/components/Flyout/flyouts/__snapshots__/flyouts.test.js.snap:24]: nevermind this would apply in the actual component, this is just the snapshot

File: public/components/Flyout/flyouts/alertsDashboard.js [hunk 3]
```diff
@@ -15,25 +23,25 @@ const alertsDashboard = (payload) => {
...
-      type: 'push',
     },
     headerProps: { hasBorder: true },
     header: (
-      <EuiText data-test-subj={`alertsDashboardFlyout_header_${trigger_name}`}>
-        <h2>{`Alerts by ${trigger_name}`}</h2>
-      </EuiText>
+      <EuiFlexGroup justifyContent="flexStart" alignItems="center">
+        <EuiFlexItem>
+          <EuiFlexGroup alignItems="center">
```
Comment (amsiglan) [inline public/components/Flyout/flyouts/alertsDashboard.js:31]: We should add the EuiTitle as the direct child, we don't need the flex group here since there is only one child

File: public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js [hunk 4]
```diff
@@ -93,17 +101,32 @@ export default class FindingFlyout extends Component {
...
         side={'right'}
         size={'m'}
       >
         <EuiFlyoutHeader hasBorder>
-          <EuiTitle size={'m'}>
-            <h2 id={findingId || `temp_finding_${docId}`}>Document finding</h2>
-          </EuiTitle>
+          <EuiFlexGroup justifyContent="flexStart" alignItems="center">
+            <EuiFlexItem>
+              <EuiFlexGroup alignItems="center">
```
Comment (amsiglan) [inline public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js:113]: Similarly here, we should simplify this by not having the flex group

File: public/components/Flyout/flyouts/alertsDashboard.js (hunk 3 above)
Comment (djindjic) [reply public/components/Flyout/flyouts/alertsDashboard.js]: done

File: public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js (hunk 4 above)
Comment (djindjic) [reply public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js]: done

File: public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js [hunk 5]
```diff
@@ -109,14 +107,10 @@ export default class FindingFlyout extends Component {
...
-            <EuiFlexItem>
-              <EuiFlexGroup alignItems="center">
-                <EuiFlexItem>
-                  <EuiTitle size={'m'}>
-                    <h3 id={findingId || `temp_finding_${docId}`}>Document finding</h3>
-                  </EuiTitle>
-                </EuiFlexItem>
-              </EuiFlexGroup>
+            <EuiFlexItem className="eui-xScrollWithShadows">
+              <EuiTitle size={'m'}>
```
Comment (amsiglan) [inline public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js:111]: Why did we add this class `eui-xScrollWithShadows`?

Comment (djindjic) [reply public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js:111]: It was one of reasons for cypress failing. Example alert/finding name was very long single word so X button was pop out of viewport. `eui-xScrollWithShadows` actually adds x-overflow on that flex item with kind of gradient for effect.

https://eui.elastic.co/v34.6.0/#/utilities/css-utility-classes#overflows

Comment (amsiglan) [reply public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js:111]: How does it look like with the scroll bar? Can you add a screenshot and tag Ming for confirmation?

Comment (djindjic) [reply public/pages/Dashboard/components/FindingsDashboard/FindingFlyout.js]: moved to `eui-textTruncate`

**Review by amsiglan — APPROVED** [review]
