### PR TITLE
[BUG] Issues in the UI above 200 destinations paging issue #195

### LINKED ISSUE #195: [BUG] Issues in the UI above 200 destinations
**Describe the bug**
I currently have more than 200 destinations in the alerting plugin and issues are noticeable : 

 - In the "Destinations" list, pagination above item 200 is broken : 
   - number of page is correct
   - if you click on a page representing an item above 200, you can quickly see the correct page but then you are redirected back to the page that is not bugged
  
- In the "Create monitor" page : 
 - if you create an action, the destination except the first 200 are not listed in the UI and you can't select them

**To Reproduce**
1. Create more than 200 destinations
2. Go to '/app/alerting#/destinations'
3. Play with the pages (1)
4. Create a monitor and a trigger
5. Start typing a destination that is not in the 200 firsts (2), it's missing

**Plugins**
Default install (everything)

**Host/Environment**
 - OS: Debian
 - Version: 10

Opensearch Dashboards 1.2.0

### PR DESCRIPTION
**Pull request by jovancacvetkovic**
### Description
Pagination and max destinations count is hardcoded to 200 items. The fix will allow all destinations to be loaded.
 
### Issues Resolved
#195
 
### Check List
- [ ] All tests pass
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/alerting-dashboards-plugin/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: public/pages/CreateTrigger/components/Action/Action.js [hunk 1]
```diff
@@ -96,7 +96,6 @@ const Action = ({
                   </React.Fragment>
                 ),
                 rowHeight: 45,
-                async: true,
```
Comment (amsiglan) [inline public/pages/CreateTrigger/components/Action/Action.js:99]: Doubt: Why did we remove the async?

File: public/utils/constants.js [hunk 2]
```diff
@@ -62,7 +62,7 @@ export const MONITOR_INPUT_DETECTOR_ID = `inputs.${INPUTS_DETECTOR_ID}`;
 
 export const AD_PREVIEW_DAYS = 7;
 
-export const MAX_QUERY_RESULT_SIZE = 200;
+export const MAX_QUERY_RESULT_SIZE = 5000;
```
Comment (amsiglan) [inline public/utils/constants.js:65]: Changing this will update the max size for all the api calls, do we only want to change it for the channels?

File: public/pages/CreateTrigger/components/Action/Action.js (hunk 1 above)
Comment (jovancacvetkovic) [reply public/pages/CreateTrigger/components/Action/Action.js:99]: @amsiglan, async in this context means filtering will be done manually, look at https://eui.elastic.co/v34.6.0/#/forms/combo-box#async. The prop is set but there is no logic added to support this and hence the combo filter was not working.
The combo gets all the data anyway and the fastest filter here is the local filter which the combo already supports. I removed async in order to use standard combo search.

File: public/utils/constants.js (hunk 2 above)
Comment (jovancacvetkovic) [reply public/utils/constants.js]: Right, I added MAX_CHANNELS_RESULT_SIZE=5000 to be used just for getting all the channels.

**Review by amsiglan — APPROVED** [review]

**Review by AWSHurneyt — APPROVED** [review]
